project:
  type: website
  output-dir: docs

website:
  title: "Annabel Coxon"
  #google-analytics: # something to come here
  site-url: https://github.com/AnnabelMC25/annabelc_notebook/blob/main/posts/_template0.qmd # you must change this appropriately for RSS feeds to work properly
  navbar:
    logo: headshots/logo.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "Lab Notebook"
        href: notebook.qmd
      - text: "Lab Handbook"
        href: https://alcalalab.github.io/resources/
      right:
      - icon: github
        href: https://github.com/AnnabelMC25/annabelc_notebook/blob/main/posts/_template0.qmd

  page-footer:
    left: |
      © 2026 Annabel Coxon

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    toc-depth: 3
    link-external-newwindow: true
    link-external-icon: false

execute:
  freeze: auto
